"""Utility modules for ab-cli."""

from ab_cli.utils.logging import (
    log_info,
    log_success,
    log_warning,
    log_error,
    log_debug,
    RED,
    GREEN,
    YELLOW,
    BLUE,
    CYAN,
    NC,
)
from ab_cli.utils.exceptions import (
    AbCliError,
    GitError,
    LLMError,
    ConfigError,
    FileOperationError,
)
from ab_cli.utils.git_helpers import (
    run_git,
    is_git_repo,
    get_repo_root,
    get_current_branch,
    is_protected_branch,
    branch_exists,
    create_branch,
    get_staged_files,
    get_unstaged_files,
    get_untracked_files,
    get_staged_diff,
    get_staged_name_status,
    stage_all_files,
    has_uncommitted_changes,
    create_commit,
    get_latest_commit,
    get_recent_commits,
    get_commit_message,
    get_commit_subject,
    get_short_hash,
    is_merge_commit,
    get_commit_diff,
    get_commit_files,
    list_commits,
    has_remotes,
    check_commits_pushed,
    get_latest_tag,
    get_all_tags,
    get_conflicted_files,
    detect_base_branch,
    get_commits_ahead,
    get_diff_against_base,
    get_commits_log,
    get_files_changed,
)
from ab_cli.utils.llm_helpers import (
    call_llm,
    call_llm_with_model_info,
    get_llm_text,
)

__all__ = [
    # Logging functions
    'log_info',
    'log_success',
    'log_warning',
    'log_error',
    'log_debug',
    # Color constants
    'RED',
    'GREEN',
    'YELLOW',
    'BLUE',
    'CYAN',
    'NC',
    # Exceptions
    'AbCliError',
    'GitError',
    'LLMError',
    'ConfigError',
    'FileOperationError',
    # Git helpers
    'run_git',
    'is_git_repo',
    'get_repo_root',
    'get_current_branch',
    'is_protected_branch',
    'branch_exists',
    'create_branch',
    'get_staged_files',
    'get_unstaged_files',
    'get_untracked_files',
    'get_staged_diff',
    'get_staged_name_status',
    'stage_all_files',
    'has_uncommitted_changes',
    'create_commit',
    'get_latest_commit',
    'get_recent_commits',
    'get_commit_message',
    'get_commit_subject',
    'get_short_hash',
    'is_merge_commit',
    'get_commit_diff',
    'get_commit_files',
    'list_commits',
    'has_remotes',
    'check_commits_pushed',
    'get_latest_tag',
    'get_all_tags',
    'get_conflicted_files',
    'detect_base_branch',
    'get_commits_ahead',
    'get_diff_against_base',
    'get_commits_log',
    'get_files_changed',
    # LLM helpers
    'call_llm',
    'call_llm_with_model_info',
    'get_llm_text',
]
